name: shoes1
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  velocity_x: ^4.1.2
  provider: any
  flutter_svg: any
  bordered_text: ^2.0.0
  animated_splash_screen: ^1.3.0
  flutter_native_splash: ^2.3.10
  line_icons: ^2.0.3
  carousel_slider: ^4.2.1
  wolt_modal_sheet: ^0.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/Others/
    - assets/images/Shoes/
    - assets/images/Splash/
    - assets/images/Svgs/
    - assets/fonts/